export enum errorTypes {
  GENERAL_ERROR = "GENERAL_ERROR",
  GENERAL_ERROR_INVERSE = "GENERAL_ERROR_INVERSE",
  FIND_ONE = "FIND_ONE",
  INSERT_ONE = "INSERT_ONE",
  UPDATE_ONE = "UPDATE_ONE",
  DELETE_ONE = "DELETE_ONE",
}
